# Stage 1: Build the application
FROM gradle:8.8-jdk22 AS builder

WORKDIR /home/gradle/project

# Copy project files
COPY . .

# Build the application
# We use installDist to create the start scripts and collect dependencies
# --no-daemon is recommended for CI/CD environments
RUN gradle installDist --no-daemon

# Stage 2: Create the runtime image
FROM amazoncorretto:22-alpine

# Set working directory
WORKDIR /app

# Copy the application from the builder stage
COPY --from=builder /home/gradle/project/build/install/yotoseek/ ./

# Create the data directory
RUN mkdir -p /data

# Set environment variables
ENV DATABASE_PATH=/data/yotoseek.db
ENV PORT=8080

# Expose the application port
EXPOSE 8080

# Define a volume for persistence
VOLUME ["/data"]

# Run the application
# The script generated by installDist is in bin/yotoseek
ENTRYPOINT ["/app/bin/yotoseek"]
